spring.application.name=web
spring.mongodb.uri=mongodb+srv://sp_db:a2Khj8sAH2opIlhT@clustersp.emizubf.mongodb.net/sp_database?appName=Clustersp

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB