spring.application.name=web
spring.mongodb.uri=mongodb+srv://sp_db:a2Khj8sAH2opIlhT@clustersp.emizubf.mongodb.net/sp_database?appName=Clustersp

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
security.auth-login-url=/api/authenticate
security.jwt-secret=n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf
security.token-header=Authorization
security.token-prefix=Bearer
security.token-type=JWT
security.token-issuer=secure-api
security.token-audience=secure-app


spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


app.storage.base-dir=C:/bioinformatics/data

# RabbitMQ Connection Settings
spring.rabbitmq.host=129.70.38.132
spring.rabbitmq.port=5672
spring.rabbitmq.username=bioadmin
spring.rabbitmq.password=zIkf87Cy

# Windows Settings (Use double backslashes)
app.r.executable=C:\\Program Files\\R\\R-4.4.2\\bin\\Rscript.exe
app.r.script-path=src\\main\\r\\deg.R